name: ampwoss
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.20.3
  - pandas=1.3.3
  - pip=21.2.2
  - scipy=1.7.1
  - sympy=1.8
  - coin-or-cbc=2.10.5
  - coin-or-clp=1.17.6
  - r-desolve=1.24
  - r-essentials=3.6.0
  - r-lintr=1.0.3
  - r-pracma=2.2.5
  - r-rootsolve=1.7
  - pip:
    - black==21.9b0
    - ciw==2.2.0
    - docformatter==1.4
    - dwys==0.0.4
    - invoke==1.6.0
    - nashpy==0.0.25
    - pulp==2.5.1
