name: ampwoss
channels:
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - r-essentials
  - r-lintr
  - r-pracma
  - pip:
      - ciw
      - dwys
      - invoke
      - black
      - docformatter
