name: ampwoss
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - python
  - scipy
  - sympy
  - r-desolve
  - r-essentials
  - r-lintr
  - r-pracma
  - r-remotes
  - r-rootSolve
  - pip:
      - ciw
      - dwys
      - invoke
      - black
      - docformatter
      - nashpy
      - pulp
