name: ampwoss
channels:
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - bwidget=1.9.11
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - cairo=1.14.12
  - cctools_osx-64=949.0.1
  - certifi=2021.5.30
  - cffi=1.14.0
  - clang=12.0.0
  - clang-12=12.0.0
  - clang_osx-64=12.0.0
  - clangxx=12.0.0
  - clangxx_osx-64=12.0.0
  - compiler-rt=12.0.0
  - compiler-rt_osx-64=12.0.0
  - curl=7.67.0
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.21.0
  - gfortran_osx-64=4.8.5
  - glib=2.63.1
  - gmp=6.2.1
  - gmpy2=2.0.8
  - graphite2=1.3.14
  - gsl=2.4
  - harfbuzz=2.4.0
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.2.0
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=7.0.1
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - krb5=1.16.4
  - ld64_osx-64=530
  - ldid=2.1.2
  - libclang-cpp12=12.0.0
  - libcurl=7.67.0
  - libcxx=12.0.0
  - libedit=3.1.20210714
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.16
  - libllvm12=12.0.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - llvm-tools=12.0.0
  - lz4-c=1.9.3
  - make=4.2.1
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.3
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - pandocfilters=1.4.3
  - pango=1.42.4
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - pixman=0.40.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.10.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - python=3.8.2
  - python-dateutil=2.8.2
  - pytz=2021.1
  - pyzmq=22.2.1
  - r-askpass=1.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-boot=1.3_20
  - r-broom=0.5.2
  - r-callr=3.2.0
  - r-caret=6.0_83
  - r-cellranger=1.1.0
  - r-class=7.3_15
  - r-cli=1.1.0
  - r-clipr=0.6.0
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=3.3
  - r-data.table=1.12.2
  - r-dbi=1.0.0
  - r-dbplyr=1.4.0
  - r-desolve=1.24
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-dplyr=0.8.0.1
  - r-ellipsis=0.1.0
  - r-essentials=3.6.0
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-forcats=0.4.0
  - r-foreach=1.4.4
  - r-foreign=0.8_71
  - r-formatr=1.6
  - r-fs=1.2.7
  - r-generics=0.0.2
  - r-ggplot2=3.1.1
  - r-glmnet=2.0_16
  - r-glue=1.3.1
  - r-gower=0.2.0
  - r-gtable=0.3.0
  - r-haven=2.1.0
  - r-hexbin=1.27.2
  - r-highr=0.8
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httpuv=1.5.1
  - r-httr=1.4.0
  - r-igraph=1.2.4.1
  - r-ipred=0.9_8
  - r-irdisplay=0.7.0
  - r-irkernel=0.8.15
  - r-iterators=1.0.10
  - r-jsonlite=1.6
  - r-kernsmooth=2.23_15
  - r-knitr=1.22
  - r-labeling=0.3
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-lava=1.6.5
  - r-lazyeval=0.2.2
  - r-lintr=1.0.3
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-maps=3.3.0
  - r-markdown=0.9
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-mime=0.6
  - r-modelmetrics=1.2.2
  - r-modelr=0.1.4
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-numderiv=2016.8_1
  - r-openssl=1.3
  - r-pbdzmq=0.3_3
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-pracma=2.2.5
  - r-praise=1.0.0
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-prodlim=2018.04.18
  - r-progress=1.2.0
  - r-promises=1.0.1
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-quantmod=0.4_14
  - r-r6=2.4.0
  - r-randomforest=4.6_14
  - r-rbokeh=0.6.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcpproll=0.3.0
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recipes=0.1.5
  - r-recommended=3.6.0
  - r-rematch=1.0.1
  - r-repr=0.19.2
  - r-reprex=0.2.1
  - r-reshape2=1.4.3
  - r-rex=1.1.2
  - r-rlang=0.3.4
  - r-rmarkdown=1.12
  - r-rootsolve=1.7
  - r-rpart=4.1_15
  - r-rstudioapi=0.10
  - r-rvest=0.3.3
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-shiny=1.3.2
  - r-sourcetools=0.1.7
  - r-spatial=7.3_11
  - r-squarem=2017.10_1
  - r-stringdist=0.9.5.1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.2
  - r-testthat=2.1.1
  - r-tibble=2.1.1
  - r-tidyr=0.8.3
  - r-tidyselect=0.2.5
  - r-tidyverse=1.2.1
  - r-timedate=3043.102
  - r-tinytex=0.12
  - r-ttr=0.23_4
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.6
  - r-xml2=1.2.0
  - r-xtable=1.8_4
  - r-xts=0.11_2
  - r-yaml=2.2.0
  - r-zoo=1.8_6
  - readline=7.0
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.33.0
  - sympy=1.8
  - tapi=1000.10.8
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.11
  - tktable=2.10
  - tornado=6.1
  - traitlets=5.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - black==21.9b0
    - ciw==2.2.0
    - click==8.0.1
    - docformatter==1.4
    - dwys==0.0.4
    - invoke==1.6.0
    - mypy-extensions==0.4.3
    - nashpy==0.0.25
    - networkx==2.6.3
    - pathspec==0.9.0
    - platformdirs==2.4.0
    - pulp==2.5.1
    - pyyaml==5.4.1
    - regex==2021.9.30
    - tomli==1.2.1
    - tqdm==4.14.0
    - typing-extensions==3.10.0.2
    - untokenize==0.1.1
