name: CI-ubuntu


on:
  push:
  pull_request:
  # Run weakly at 00:00 on Sunday.
  schedule:
  - cron:  '0 0 * * 0'

# This job installs dependencies, build the site, and pushes it to `gh-pages``
jobs:
  test:
    #runs-on: [ubuntu-latest, macOS-latest]  # TODO Add check for macOS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda
      uses: s-weigand/setup-conda@v1
    - name: Install environment
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        #Useful for debugging any issues with conda
        conda info -a
        conda env create -f environment.yml
        source activate ampwoss
        inv env  # Finish install of environment
        sudo apt-get install aspell aspell-en #To check spelling

    - name: Doctest
      run: |
        source activate ampwoss
        inv doctest --style  # Test all code and also check style
